- hosts: all
  remote_user: root
  vars_files:
    - vars.yml
  tasks:
    - name: Set up Nginx
      include_tasks: nginx.yml

    - name: Set up systemd service
      include_tasks: systemd.yml
      
    - name: Deploy new version
      include_tasks: deploy.yml