- hosts: all
  remote_user: root
  vars_files:
    - vars.yml
  tasks:
    - name: Set up Nginx
      include_tasks: tasks/nginx.yml
      
    - name: Deploy new version
      include_tasks: tasks/deploy.yml