- name: Create webroot
  ansible.builtin.file:
    path: /var/www/{{ name }}
    owner: www
    group: www
    mode: "0500"
    state: directory
  become: true

- name: Create repo directory
  ansible.builtin.file:
    path: /var/www/{{ name }}/repo
    owner: www
    group: www
    mode: "0500"
    state: directory
  become: true

- name: Create nginx site file
  ansible.builtin.template:
    src: ../files/nginx
    dest: /etc/nginx/sites-available/{{ name }}
    owner: root
    group: root
    mode: "0744"
  become: true
  register: nginx_site

- name: Stat nginx site symlink
  ansible.builtin.stat: 
    path: /etc/nginx/sites-enabled/{{ name }}
  become: true
  register: nginx_site_stat

- name: Create symlink for nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ name }}
    dest: /etc/nginx/sites-enabled/{{ name }}
    owner: root
    group: root
    mode: "0744"
    state: link
  become: true
  when: not nginx_site_stat.stat.exists

- name: Verify nginx site file
  ansible.builtin.command: nginx -t
  become: true
  when: nginx_site.changed

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx.service
    state: restarted
    scope: system
    enabled: true
  become: true
  when: nginx_site.changed