name: Apply Push to Dev

on:
  push:
    branches:
      - main

env:
  SSH_KEY_DEV: ${{ secrets.SSH_KEY_DEV }}
  SSH_HOST_DEV: ${{ secrets.SSH_HOST_DEV }}
  SSH_USER_DEV: ${{ secrets.SSH_USER_DEV }}
  SSH_SUDO_DEV: ${{ secrets.SSH_SUDO_DEV }}
  ANSIBLE_VAULT_K_DEV: ${{ secrets.ANSIBLE_VAULT_K_DEV }}
  SA_DEV: ${{ secrets.SA_DEV }}
  BUCKET_DEV: ${{ secrets.BUCKET_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Prepare to run Ansible
        run: . main/ci/scripts/prep.sh
      - name: Execute Ansible playbook (DEV)
        run: . main/ci/scripts/ansible-execute.sh DEV