name: Apply Push to Dev

on:
  push:
    branches:
      - main

env:
  SECRETS_DEV: ${{ secrets.DEV }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Prepare to run Ansible
        run: . main/ci/scripts/prep.sh
      - name: Execute Ansible playbook (DEV)
        run: . main/ci/scripts/ansible-execute.sh DEV