name: Check PR

on:
  pull_request:
    branches:
      - main

env:
  SSH_KEY_DEV: ${{ secrets.SSH_KEY_DEV }}
  SSH_HOST_DEV: ${{ secrets.SSH_HOST_DEV }}
  SSH_USER_DEV: ${{ secrets.SSH_USER_DEV }}
  SSH_SUDO_DEV: ${{ secrets.SSH_SUDO_DEV }}
  ANSIBLE_VAULT_K_DEV: ${{ secrets.ANSIBLE_VAULT_K_DEV }}
  SA_DEV: ${{ secrets.SA_DEV }}
  BUCKET_DEV: ${{ secrets.BUCKET_DEV }}

  SSH_KEY_PROD: ${{ secrets.SSH_KEY_PROD }}
  SSH_HOST_PROD: ${{ secrets.SSH_HOST_PROD }}
  SSH_USER_PROD: ${{ secrets.SSH_USER_PROD }}
  SSH_SUDO_PROD: ${{ secrets.SSH_SUDO_PROD }}
  ANSIBLE_VAULT_K_PROD: ${{ secrets.ANSIBLE_VAULT_K_PROD }}
  SA_PROD: ${{ secrets.SA_PROD }}
  BUCKET_PROD: ${{ secrets.BUCKET_PROD }}

  

jobs:
  build:
    name: Check Ansible changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: pr
      - name: Prepare to run Ansible
        run: . main/ci/scripts/prep.sh
      - name: Check Ansible playbook (DEV)
        run: . main/ci/scripts/ansible-check.sh DEV
      - name: Check Ansible playbook (PROD)
        run: . main/ci/scripts/ansible-check.sh PROD